### ISSUE TITLE
playback log folder

### ISSUE THREAD

**Issue by dlliu0422** [kevin1997998/pegatron#5]
在request.py的過程所產生的log資料,不要跟script 的混在一起,建議在script file folder建議一個新目錄存放,(目錄名稱可以用目前時間當名稱)

**Comment by Weile0409** [comment]
已解決，使用範例如下：
```python main.py --dir_path firestrike/record ```，即把App的輸出儲存至```firestrike/record```
```python request.py --dir_path firestrik/record --res_path firestrike/result```，即讀取```firestrike/record```裡的模板、log.txt，並把辨識結果儲存至```firestrike/result```
